# #####################################################################
# Automatically generated by qmake (2.01a) Fri May 1 19:49:51 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += jsonstreamreader.h
SOURCES += jsonstreamreader.cpp \
    main.cpp
